name: Notify Discord of Deployment

on:
  deployment

env:
    ADDED_FILES: ''
    MODIFIED_FILES: ''
    FINAL_MESSAGE: ''

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get all new files and use a newline separator
      id: all-files
      uses: tj-actions/changed-files@v38
      with:
        separator: '\n' # note the space before the newline
      #  dir_names_include_files: 'true'
        files: |
          **/*.txt
    - name: Append new files to ADDED_FILES
      run: echo "ADDED_FILES=${{ steps.all-files.outputs.added_files }} >> $GITHUB_ENV
    - name: Append modified files to MODIFIED_FILES
      run: echo "MODIFIED_FILES=${{ steps.all-files.outputs.modified_files }} >> $GITHUB_ENV
    - name: Append renamed files to MODIFIED_FILES
      run: echo "MODIFIED_FILES=${{ env.MODIFIED_FILES }}\n${{ steps.all-files.outputs.modified_files }} >> $GITHUB_ENV
    - name: Remove all .txt strings from FILES
      run: |
        echo "ADDED_FILES=${{ env.ADDED_FILES//.txt/ }} >> $GITHUB_ENV
        echo "MODIFIED_FILES=${{ env.MODIFIED_FILES//.txt/ }} >> $GITHUB_ENV
    - name: Format message
      id: formatted-message
      run: echo "FINAL_MESSAGE=Parawatch web crawlers have detected an adjustment to the main database.\n\nInvestigation in origins and intent of change is ongoing.\n\nNEW DOCUMENTS DETECTED:\n${{env.ADDED_FILES}}\n\nCHANGED DOCUMENTS DETECTED:\n${{env.MODIFIED_FILES}}\n\nParawatch database accessible via [your Parawatch Client](https://project-untold.github.io)" >> $GITHUB_ENV
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: ${{secrets.DISCORD_WEBHOOK_KEY}}
        method: 'POST'
        avatar_url: 'https://pbs.twimg.com/profile_images/1175910721843941378/ixp9VdIk_400x400.jpg'
        username: 'Parawatch Notification Centre'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{
                "content": "<@&1146147442383925378>",
                "embeds": [
                  {
                    "title": "Parawatch Database Change Detected",
                    "description": "${{ env.FINAL_MESSAGE }}",
                    "url": "https://project-untold.github.io",
                    "color": 4915387
                  }
                ],
                "attachments": []
              }'