name: Notify Discord of Deployment

on:
  deployment

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://discord.com/api/webhooks/1089996213585182831/g3ehzjNB4E7iqu2oqnI3j3jm5Ax7gexM0yskEOwI-SStAtws1YXx1ZGtQsE7-INaKz35'
        method: 'POST'
        avatar_url: 'https://pbs.twimg.com/profile_images/1175910721843941378/ixp9VdIk_400x400.jpg'
        username: 'Parawatch Notification Centre'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{
                "content": null,
                "embeds": [
                  {
                    "title": "Parawatch Database Change Detected",
                    "description": "Parawatch web crawlers have detected an adjustment to the main database.\n\nInvestigation in origins and intent of change is ongoing.\n\nParawatch database accessible via [your Parawatch Client](https://project-untold.github.io)",
                    "url": "https://project-untold.github.io",
                    "color": 4915387
                  }
                ],
                "attachments": []
              }'