name: Notify Discord of Deployment

on:
  deployment

env:
    ADDED_FILES: ''
    MODIFIED_FILES: ''
    FINAL_MESSAGE: ''

jobs:
  filesprep:
    name: Prepare files
    runs-on: ubuntu-latest
    outputs:
      run-deployment: ${{ steps.run-deployment.outputs.run-deployment }}
      added_files: ${{ steps.added-files.outputs.added_files }}
      modified_files: ${{ steps.modified-files.outputs.modified_files }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get all new files and use a newline separator
      id: all-files
      uses: tj-actions/changed-files@v38
      with:
        separator: '\n'
      #  dir_names_include_files: 'true'
        files: |
          **/*.txt
    - id: added-files
      name: Append new files to ADDED_FILES
      run: echo "added_files=${{ steps.all-files.outputs.added_files }}" >> $GITHUB_OUTPUT
    - id: modified-files
      name: Append modified files to MODIFIED_FILES
      run: echo "modified_files=${{ steps.all-files.outputs.modified_files }}" >> $GITHUB_OUTPUT
    - id: run-deployment
      name: Check if deployment should run
      run: echo "run-deployment=${{ steps.added-files.outputs.added_files != '' && steps.modified-files.outputs.modified_files != '' }}" >> $GITHUB_OUTPUT

  deployment:
    runs-on: ubuntu-latest
    needs: filesprep
    if: ${{ needs.filesprep.outputs.run-deployment == 'true' }}
    steps:
    - name: Remove all .txt strings from FILES
      run: |
        ADDED_FILES_WITHOUT_TXT=$(echo ${{needs.filesprep.outputs.added_files}} | sed 's/\.txt//g')
        echo "ADDED_FILES=$ADDED_FILES_WITHOUT_TXT" >> $GITHUB_ENV
        MODIFIED_FILES_WITHOUT_TXT=$(echo ${{needs.filesprep.outputs.modified_files}} | sed 's/\.txt//g')
        echo "MODIFIED_FILES=$MODIFIED_FILES_WITHOUT_TXT" >> $GITHUB_ENV
    - name: Format message
      id: formatted-message
      run: echo "FINAL_MESSAGE=Parawatch web crawlers have detected an adjustment to the main database.\n\nInvestigation in origins and intent of change is ongoing.\n\nNEW DOCUMENTS DETECTED:\n${{env.ADDED_FILES}}\n\nCHANGED DOCUMENTS DETECTED:\n${{env.MODIFIED_FILES}}\n\nParawatch database accessible via [your Parawatch Client](https://project-untold.github.io)" >> $GITHUB_ENV

   # - name: Deploy Stage
    #  uses: fjogeleit/http-request-action@v1
     # with:
      #  url: ${{secrets.DISCORD_WEBHOOK_KEY}}
       # method: 'POST'
        # avatar_url: 'https://pbs.twimg.com/profile_images/1175910721843941378/ixp9VdIk_400x400.jpg'
        #username: 'Parawatch Notification Centre'
        #customHeaders: '{"Content-Type": "application/json"}'
        #data: '{
         #       "content": "<@&1146147442383925378>",
          #      "embeds": [
           #       {
            #        "title": "Parawatch Database Change Detected",
             #       "description": "${{ env.FINAL_MESSAGE }}",
              #      "url": "https://project-untold.github.io",
               #     "color": 4915387
                #  }
               # ],
               # "attachments": []
              #}'